version: "3"
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3000"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Momen@@010
      DB_NAME: whatsapp
      PORT: 3000
      ACCESS_SECRET: abcdefghigk
      EMAIL_USER: momenelmesady4803@gmail.com
      EMAIL_PASS: wlvb wyrd rqng evwu
      REFRESH_SECRET: abcdefghigk

  chat-service:
    build: ./chat-service
    ports:
      - "3002:3000"
    volumes:
      - ./chat-service:/app
      - /app/node_modules
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: Momen@@010
      DB_NAME: whatsapp
      PORT: 3000
      ACCESS_SECRET: abcdefghigk
      RABBITMQ_HOST: rabbitmq

  notification-service:
    build: ./notification-service
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - user-service
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Momen@@010
      DB_NAME: whatsapp
      RABBITMQ_URL: amqp://rabbitmq
      RABBITMQ_HOST: rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user-service
      - chat-service
      - notification-service
