version: "3"
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3000"
    # depends_on:
    #   - mysql
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Momen@@010
      DB_NAME: whatsapp
      PORT: 3000
      ACCESS_SECRET: abcdefghigk
      EMAIL_USER: momenelmesady4803@gmail.com
      EMAIL_PASS: wlvb wyrd rqng evwu
      REFRESH_SECRET: abcdefghigk

  chat-service:
    build: ./chat-service
    ports:
      - "3002:3000"
    # depends_on:
    #   - mysql
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: Momen@@010
      DB_NAME: whatsapp
      PORT: 3000
      ACCESS_SECRET: abcdefghigk
      RABBITMQ_HOST: rabbitmq


  # mysql:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Momen@@010
  #     MYSQL_DATABASE: whatsapp
  #   # ports:
  #   #   - "3306:3306"


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # للـ RabbitMQ broker
      - "15672:15672"   # للـ UI بتاع RabbitMQ
  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq
      - user-service  # لو بيحتاج يقرأ fcm_token من قاعدة بيانات user
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Momen@@010
      DB_NAME: whatsapp
      RABBITMQ_URL: amqp://rabbitmq
      RABBITMQ_HOST: rabbitmq

    restart: always

  

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user-service
      - chat-service
